name: Action Workflow

on: [push]

jobs:
    run-github-Action:
      runs-on: ubuntu-latest
      steps:
        - name: simple javascript jaction
          uses: actions/hello-world-javascript-action@main
          with:
            who-to-greet: 'Mona the Octocat'
